version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_database:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=app_databse_user
      - POSTGRES_PASSWORD=8Tch2hC9OPiPavW8FnXedoMDIF42lkI8
      - POSTGRES_DB=app_databse
    ports:
      - 5432:5433

    restart: always


  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
 
    depends_on:
        - "app_database"
    environment: 
         - ConnectionStrings:DefaultConnection="Host=dpg-cqt8uq5ds78s738egr10-a;Database=app_databse;Username=app_databse_user;Password=8Tch2hC9OPiPavW8FnXedoMDIF42lkI8;Port=5432;"
         - ASPNETCORE_URLS=http://+80;


