version: '3.4'


services:

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  app_database:
    image: postgres:latest
    container_name: app_db
    environment:
      - POSTGRES_USER=ecomm_database_oai5_user
      - POSTGRES_PASSWORD=KEWnfNqFNWVNsJC8S1P5nBDitPXvdDns
      - POSTGRES_DB=ecomm_database_oai5
    ports:
      - 5432:5433

    restart: always


  taskmanager.api:
    image: ${DOCKER_REGISTRY-}taskmanagerapi
    build:
      context: .
      dockerfile: TaskManagerApi/Dockerfile
 
    depends_on:
        - "app_database"
    environment: 
         - ConnectionStrings:DefaultConnection="Host=dpg-cqt7bs2j1k6c73bv4uv0-a.oregon-postgres.render.com;Database=ecomm_database_oai5;Username=ecomm_database_oai5_user;Password=KEWnfNqFNWVNsJC8S1P5nBDitPXvdDns;Port=5432;"
         - ASPNETCORE_URLS=http://+80;


